service: dog
image: alca42/dog

servers:
  web:
    - 49.13.146.41

proxy:
  ssl: true
  host: ethogram.dog
  app_port: 4000

registry:
  username: alca42

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    VITE_PUBLIC_SERVER: "https://z.ethogram.dog"

accessories:
  zero:
    image: rocicorp/zero:0.18.2025040300
    roles:
      - web
    env:
      clear:
        ZERO_REPLICA_FILE: "/data/replica.db"
        # ZERO_APP_ID: "dog"
      secret:
        - ZERO_UPSTREAM_DB
        - ZERO_CVR_DB
        - ZERO_CHANGE_DB
        - ZERO_AUTH_SECRET
    proxy:
      ssl: true
      host: z.ethogram.dog
      app_port: 4848
      healthcheck:
        interval: 5
        path: "/"
        timeout: 3
    directories:
      - data:/data

  postgres:
    image: postgres:17.4-alpine
    roles:
      - web
    env:
      clear:
        POSTGRES_USER: "dog"
        POSTGRES_DB: "dog"
        POSTGRES_HOST_AUTH_METHOD: "md5"
        POSTGRES_INITDB_ARGS: "--auth-host=md5"
      secret:
        - POSTGRES_PASSWORD
    cmd: |
      postgres \
        -c wal_level=logical \
        -c max_wal_senders=10 \
        -c max_replication_slots=5 \
        -c hot_standby=on \
        -c hot_standby_feedback=on
    port: "5444:5432"
    directories:
      - data:/var/lib/postgresql/data
